---
trigger: none

variables:
  - group: Terraform-Variable-Group

stages:
    - stage: terraform
      displayName: Build infrastructure
      jobs:
      - job: Terraform_Plan
        displayName: Terraform Init, Plan & Apply
        pool:
          name: pipeline-agent
        steps:
          - template: terraform.yml
    - stage: BuildApp
      displayName: Build webapp
      jobs:
      - job: buildapp
        displayName: build app
        pool:
          name: pipeline-agent
        steps:
          - task: SonarQubePrepare@5
            inputs:
              SonarQube: 'SonarQube'
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: 'MultiAppSlot_MultiAppSlot_AYD2ZFd6jCAKRy53Gje4'
              cliProjectName: 'sonar.projectName'
              cliSources: '.'
          - template: buildapp.yml
          - task: SonarQubeAnalyze@5
          - task: SonarQubePublish@5
            inputs:
              pollingTimeoutSec: '300'

    - stage: DeployApp
      displayName: Deploy app
      jobs:
      - job: Deployapp
        displayName: Deploy app
        pool:
          name: pipeline-agent
        steps:
          - template: deploy.yml
