---
trigger: none

variables:
  - group: Terraform-Variable-Group

stages:
    - stage: terraform
      displayName: Build infrastructure
      jobs:
      - job: Terraform_Plan
        displayName: Terraform Init, Plan & Apply
        pool:
          name: pipeline-agent
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'AzureSC'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'az login'
          - template: terraform.yml
              
    - stage: BuildApp
      displayName: Build webapp
      jobs:
      - job: buildapp
        displayName: build app
        pool:
          name: pipeline-agent
        steps:
          - template: buildapp.yml

    - stage: DeployApp
      displayName: Deploy app
      jobs:
      - job: Deployapp
        displayName: Deploy app
        pool:
          name: pipeline-agent
        steps:
          - template: deploy.yml