---
trigger: none
variables:
  - group: Terraform-Variable-Group
stages:
    - stage: terraform
      displayName: Build infrastructure
      jobs:
      - job: Terraform_Plan
        displayName: Terraform Init, Plan & Apply
        pool:
          name: My-AKS-Pool
        steps:
          - template: terraform.yml
              
    - stage: BuildApp
      displayName: Build webapp
      jobs:
      - job: buildapp
        displayName: build app
        pool:
          vmImage: windows-latest
        steps:
          - template: buildapp.yml

    - stage: DeployApp
      displayName: Deploy app
      jobs:
      - job: Deployapp
        displayName: Deploy app
        pool:
          name: My-AKS-Pool
        steps:
          - template: deploy.yml